[package]
name = "HackerOne"
version = "1.0.0"
authors = []

[addresses]
hackerOne = "c36a72f1ef8b723624bf9801c98d3f17ddf492266a508a9986f516d10f4dd464"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
