[package]
name = "HackerOne"
version = "1.0.0"
authors = []

[addresses]
hackerOne = "8605dbe75af9038d2f9061e419879c98d831d93f7e5b9a5951826126b83aa60a"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
